'use server'

import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { revalidatePath } from 'next/cache'

export interface InvoiceLineItem {
  item_name: string
  description?: string
  quantity: number
  unit_price: number
  discount_percent?: number
  tax_percent?: number
  service_id?: string
}

export async function createInvoice(data: {
  patient_id: string
  invoice_type: string
  invoice_date: string
  due_date?: string
  items: InvoiceLineItem[]
  discount_percent?: number
  discount_amount?: number
  discount_reason?: string
  notes?: string
  appointment_id?: string
}) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const { data: profile } = await supabase
    .from('profiles')
    .select('id, hospital_id')
    .eq('auth_user_id', user.id)
    .single()
  if (!profile) throw new Error('Profile not found')

  const admin = createAdminClient()

  // Compute totals
  const subtotal = data.items.reduce((sum, item) => {
    const lineTotal = item.quantity * item.unit_price
    const disc = lineTotal * ((item.discount_percent ?? 0) / 100)
    return sum + lineTotal - disc
  }, 0)

  const discountAmt = data.discount_amount ?? (subtotal * ((data.discount_percent ?? 0) / 100))

  const taxAmount = data.items.reduce((sum, item) => {
    const lineTotal = item.quantity * item.unit_price
    const disc = lineTotal * ((item.discount_percent ?? 0) / 100)
    const taxable = lineTotal - disc
    return sum + taxable * ((item.tax_percent ?? 0) / 100)
  }, 0)

  const totalAmount = subtotal - discountAmt + taxAmount

  const { data: invoice, error: invErr } = await admin
    .from('hospital_invoices')
    .insert({
      hospital_id:      profile.hospital_id,
      patient_id:       data.patient_id,
      appointment_id:   data.appointment_id   || null,
      invoice_number:   '',                   // auto-generated by DB trigger
      invoice_date:     data.invoice_date,
      invoice_type:     data.invoice_type,
      due_date:         data.due_date         || null,
      subtotal:         subtotal,
      discount_percent: data.discount_percent ?? 0,
      discount_amount:  discountAmt,
      discount_reason:  data.discount_reason  || null,
      tax_amount:       taxAmount,
      total_amount:     totalAmount,
      paid_amount:      0,
      status:           'pending',
      notes:            data.notes            || null,
      created_by:       profile.id,
    })
    .select('id, invoice_number')
    .single()

  if (invErr) throw new Error(invErr.message)

  // Insert line items
  if (data.items.length > 0) {
    const lineItems = data.items.map((item, idx) => {
      const lineTotal = item.quantity * item.unit_price
      const discAmt = lineTotal * ((item.discount_percent ?? 0) / 100)
      const taxAmt = (lineTotal - discAmt) * ((item.tax_percent ?? 0) / 100)
      return {
        hospital_id:      profile.hospital_id,
        invoice_id:       invoice.id,
        service_id:       item.service_id || null,
        item_name:        item.item_name,
        description:      item.description || null,
        quantity:         item.quantity,
        unit:             'unit',
        unit_price:       item.unit_price,
        discount_percent: item.discount_percent ?? 0,
        discount_amount:  discAmt,
        tax_percent:      item.tax_percent ?? 0,
        tax_amount:       taxAmt,
        total_amount:     lineTotal - discAmt + taxAmt,
        sort_order:       idx + 1,
      }
    })

    const { error: itemsErr } = await admin
      .from('invoice_items')
      .insert(lineItems)

    if (itemsErr) throw new Error(itemsErr.message)
  }

  revalidatePath('/app/billing')
  return { id: invoice.id, invoice_number: invoice.invoice_number }
}

export async function recordPayment(data: {
  invoice_id: string
  patient_id: string
  amount: number
  payment_method: string
  reference_number?: string
  notes?: string
}) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const { data: profile } = await supabase
    .from('profiles').select('id, hospital_id').eq('auth_user_id', user.id).single()
  if (!profile) throw new Error('Profile not found')

  const admin = createAdminClient()

  const { error } = await admin
    .from('payments')
    .insert({
      hospital_id:      profile.hospital_id,
      patient_id:       data.patient_id,
      invoice_id:       data.invoice_id,
      payment_number:   '',                       // auto-generated by DB trigger
      amount:           data.amount,
      payment_method:   data.payment_method,
      reference_number: data.reference_number || null,
      notes:            data.notes            || null,
      status:           'completed',
      paid_at:          new Date().toISOString(),
      collected_by:     profile.id,
    })

  if (error) throw new Error(error.message)
  // DB trigger auto-updates invoice paid_amount + status
  revalidatePath('/app/billing')
}

export async function voidInvoice(invoiceId: string, reason: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const admin = createAdminClient()
  const { error } = await admin
    .from('hospital_invoices')
    .update({ status: 'void', void_reason: reason, voided_at: new Date().toISOString() })
    .eq('id', invoiceId)

  if (error) throw new Error(error.message)
  revalidatePath('/app/billing')
}
