'use server'

import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { revalidatePath } from 'next/cache'

export async function createPatient(data: {
  full_name: string
  gender?: string
  date_of_birth?: string
  blood_group?: string
  phone?: string
  alternate_phone?: string
  email?: string
  address_line1?: string
  address_line2?: string
  city?: string
  state?: string
  pincode?: string
  marital_status?: string
  occupation?: string
  insurance_provider?: string
  insurance_policy_no?: string
  notes?: string
}) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const { data: profile } = await supabase
    .from('profiles')
    .select('id, hospital_id')
    .eq('auth_user_id', user.id)
    .single()

  if (!profile) throw new Error('Profile not found')

  const admin = createAdminClient()

  const { data: patient, error } = await admin
    .from('patients')
    .insert({
      hospital_id:         profile.hospital_id,
      mrn:                 '', // auto-generated by DB trigger
      full_name:           data.full_name.trim(),
      gender:              data.gender              || null,
      date_of_birth:       data.date_of_birth       || null,
      blood_group:         data.blood_group         || null,
      phone:               data.phone               || null,
      alternate_phone:     data.alternate_phone     || null,
      email:               data.email               || null,
      address_line1:       data.address_line1       || null,
      address_line2:       data.address_line2       || null,
      city:                data.city                || null,
      state:               data.state               || null,
      pincode:             data.pincode             || null,
      marital_status:      data.marital_status      || null,
      occupation:          data.occupation          || null,
      insurance_provider:  data.insurance_provider  || null,
      insurance_policy_no: data.insurance_policy_no || null,
      notes:               data.notes               || null,
      registered_by:       profile.id,
    })
    .select('id, mrn')
    .single()

  if (error) throw new Error(error.message)

  revalidatePath('/app/patients')
  return { id: patient.id, mrn: patient.mrn }
}

export async function deletePatient(patientId: string) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) throw new Error('Not authenticated')

  const admin = createAdminClient()
  const { error } = await admin
    .from('patients')
    .update({ deleted_at: new Date().toISOString(), is_active: false })
    .eq('id', patientId)

  if (error) throw new Error(error.message)
  revalidatePath('/app/patients')
}
